version: "3.8"
services:
  apache:
    container_name: apache
    build: ./apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ../App:/usr/local/apache2/htdocs
  php:
    container_name: php
    build: ./php
    env_file:
      ./.env 
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ../App:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    env_file:
      ./.env 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    env_file:
      ./.env 
    restart: always
    ports:
      - 8085:80